name: Build

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update python dependencies for api
        run: ./api/update-dep.sh

      - name: Update python dependencies for worker
        run: ./worker/update-dep.sh

      - name: Create dist
        run: make dist

      - name: Rename dist
        run: mv dist/site1-*.tar.gz dist/site1.tar.gz

      # https://github.com/softprops/action-gh-release
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "dist/site1.tar.gz"
          fail_on_unmatched_files: true
